'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { fetchProtectedJson, getCurrentUser, isUnauthorizedError } from '../../lib/authApi';
import type { LearningAggregate, LearningOverviewResponse } from '../../lib/apiTypes';

const practiceHref = (topic: string, subtopic: string) => `/practice/topic/${topic}?subtopic=${subtopic}`;
const confidenceLabel = (value: LearningAggregate['confidence']): string => value === 'usable' ? 'Đủ dữ liệu' : value === 'low' ? 'Cần thêm dữ liệu' : 'Chưa đủ dữ liệu';
const topicIcon = (index: number) => ['∫', '△', '⌁', 'Σ', 'π', 'aₙ'][index % 6];

function MasteryRing({ value }: { value: number | null }) { const percentage = value ?? 0; const radius = 42; const circumference = 2 * Math.PI * radius; return <div className="relative flex h-28 w-28 items-center justify-center"><svg className="-rotate-90" width="112" height="112" viewBox="0 0 112 112" aria-hidden="true"><circle cx="56" cy="56" r={radius} fill="none" stroke="currentColor" strokeWidth="9" className="text-background-alt" /><circle cx="56" cy="56" r={radius} fill="none" stroke="currentColor" strokeWidth="9" strokeLinecap="round" className="text-primary" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - percentage / 100)} /></svg><span className="absolute text-2xl font-bold tracking-tight text-text-primary">{value === null ? '—' : `${value}%`}</span></div>; }
function MetricIcon({ children, tone = 'blue' }: { children: React.ReactNode; tone?: 'blue' | 'green' }) { return <span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-lg font-bold ${tone === 'green' ? 'bg-success-light text-success' : 'bg-primary-light text-primary'}`}>{children}</span>; }

export function LearningDashboardClient() {
  const [data, setData] = useState<LearningOverviewResponse | null>(null); const [state, setState] = useState<'loading' | 'guest' | 'error' | 'ready'>('loading');
  useEffect(() => { let active = true; void (async () => { try { if (!await getCurrentUser()) { if (active) setState('guest'); return; } const result = await fetchProtectedJson<LearningOverviewResponse>('/api/me/learning-overview'); if (active) { setData(result); setState('ready'); } } catch (error) { if (active) setState(isUnauthorizedError(error) ? 'guest' : 'error'); } })(); return () => { active = false; }; }, []);
  if (state === 'loading') return <main className="min-h-[60vh] p-8 text-text-secondary">Đang tải tiến độ học tập…</main>;
  if (state === 'guest') return <main className="mx-auto max-w-3xl p-8"><h1 className="workspace-page-title">Luyện thi Toán cùng ManMath</h1><p className="workspace-page-description mt-3">Đăng nhập để lưu tiến độ, nhận gợi ý luyện tập và theo dõi mastery.</p><Link className="workspace-button-text mt-6 inline-flex rounded-lg bg-primary px-5 py-3 text-white" href="/exams">Khám phá kho đề</Link></main>;
  if (state === 'error' || data === null) return <main className="p-8 text-error">Không tải được dashboard. Hãy thử lại sau.</main>;
  const { overall, nextAction, continueItems, recentActivity, subtopics, topics } = data; const weak = subtopics.filter((item) => item.isWeak).slice(0, 2); const visibleTopics = topics.filter((item) => item.answeredCount > 0).slice(0, 8);
  return <main className="mx-auto w-full max-w-[1280px] space-y-5 px-4 py-7 sm:px-6 lg:px-8"><header><p className="workspace-eyebrow text-primary">Không gian học tập</p><h1 className="workspace-page-title mt-1 text-text-primary">Tiến độ luyện thi của bạn</h1><p className="workspace-page-description mt-2">Mastery dựa trên điểm đã chấm; số câu đã trả lời giải thích độ tin cậy.</p></header>
    <section className="rounded-2xl border border-border bg-surface p-5 shadow-card sm:p-6"><div className="grid gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(220px,.78fr)_minmax(220px,.78fr)] lg:items-center"><div className="flex items-center gap-5"><MasteryRing value={overall.masteryPercent} /><div><p className="text-xl font-bold text-text-primary">Mastery tổng quan</p><p className="workspace-metadata mt-3">{overall.answeredCount} câu đã trả lời <span className="px-1.5 text-primary">•</span> {overall.examQuestionCount} từ đề <span className="px-1.5 text-primary">•</span> {overall.practiceQuestionCount} từ luyện tập</p></div></div><div className="border-t border-border pt-5 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><div className="flex items-center gap-3"><MetricIcon>⌾</MetricIcon><div><p className="workspace-metadata">Độ tin cậy</p><p className="mt-1 text-base font-bold text-text-primary">{confidenceLabel(overall.confidence)}</p></div></div><p className="workspace-metadata mt-3 leading-5">Câu bỏ trống làm giảm mastery nhưng không tăng mẫu đánh giá.</p></div><div className="border-t border-border pt-5 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><div className="flex items-center gap-3"><MetricIcon tone="green">◎</MetricIcon><div><p className="workspace-metadata">Tiến độ theo nguồn</p><p className="mt-1 text-base font-bold text-text-primary">{overall.fullyCorrectCount} câu đúng hoàn toàn</p></div></div><p className="workspace-metadata mt-3">Điểm: {overall.earnedScoreUnits}/{overall.maxScoreUnits} score units</p></div></div></section>
    <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="relative overflow-hidden rounded-2xl border border-primary/25 bg-primary-light/35 p-6"><span className="absolute -bottom-8 right-5 text-8xl font-bold text-primary/10" aria-hidden="true">◎</span><div className="relative"><div className="flex items-center gap-3"><MetricIcon>↗</MetricIcon><h2 className="workspace-section-title text-primary">Bước tiếp theo</h2></div>{nextAction ? <><p className="mt-5 text-lg font-bold text-text-primary">{nextAction.title}</p><p className="workspace-page-description mt-2 max-w-xl">{nextAction.reason}</p><Link className="workspace-button-text mt-5 inline-flex h-10 items-center justify-center rounded-lg bg-primary px-4 text-white transition hover:bg-primary-hover" href={practiceHref(nextAction.topicSlug, nextAction.subtopicSlug)}>Luyện 5 câu <span className="ml-2">→</span></Link></> : <p className="workspace-page-description mt-5">Corpus chưa có subtopic đủ câu để đề xuất.</p>}{continueItems[0] ? <Link href={`/practice/topic/${continueItems[0].topicSlug}`} className="workspace-button-text relative mt-4 block text-sm text-primary hover:text-primary-hover">Tiếp tục: {continueItems[0].title} →</Link> : null}</div></article><article className="rounded-2xl border border-warning-border bg-warning-light/35 p-6"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-warning text-lg text-white">!</span><h2 className="workspace-section-title text-text-primary">Cần chú ý</h2></div>{weak.length ? <div className="mt-5 space-y-3">{weak.map((item) => <Link key={item.subtopicSlug} href={practiceHref(item.topicSlug, item.subtopicSlug!)} className="block text-sm font-semibold text-text-primary hover:text-primary">{item.subtopicName}<span className="workspace-metadata"> · {item.masteryPercent ?? '—'}% · {item.answeredCount} câu đã trả lời</span></Link>)}</div> : <p className="workspace-page-description mt-5">Chưa có phần nào đủ dữ liệu để kết luận là cần luyện thêm.</p>}</article></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-surface shadow-card"><header className="flex items-center justify-between border-b border-border px-5 py-4"><div className="flex items-center gap-2"><span className="text-primary">▧</span><h2 className="workspace-section-title text-text-primary">Hoạt động gần đây</h2></div><Link href="/history" className="workspace-button-text text-sm text-primary hover:text-primary-hover">Xem tất cả</Link></header>{recentActivity.length ? <div className="divide-y divide-border">{recentActivity.map((item) => <div className="flex items-center gap-3 px-5 py-3" key={`${item.sourceType}-${item.id}`}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-background-alt text-xs text-primary">{item.sourceType === 'exam' ? 'Đ' : 'L'}</span><p className="min-w-0 flex-1 truncate text-sm text-text-primary"><span className="font-medium">{item.sourceType === 'exam' ? 'Đề' : 'Luyện tập'}</span> <span className="text-text-muted">·</span> {item.title}</p><span className="shrink-0 text-sm font-medium text-text-secondary">{item.fullyCorrectCount}/{item.totalQuestions} đúng hoàn toàn</span><span className="text-text-muted">›</span></div>)}</div> : <p className="workspace-page-description px-5 py-7">Chưa có hoạt động hoàn thành. Hãy bắt đầu một phiên luyện tập.</p>}</section>
    <section className="rounded-2xl border border-border bg-surface p-5 shadow-card"><div className="flex items-center gap-2"><span className="text-primary">▤</span><h2 className="workspace-section-title text-text-primary">Tiến độ theo chuyên đề</h2></div>{visibleTopics.length ? <div className="mt-4 grid gap-2.5 sm:grid-cols-2">{visibleTopics.map((item, index) => { const percent = item.masteryPercent ?? 0; return <div key={item.topicSlug} className="flex items-center gap-3 rounded-xl bg-background-alt/55 px-3 py-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary-light text-sm font-bold text-primary">{topicIcon(index)}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-semibold text-text-primary">{item.topicName}</p><span className="text-xs font-bold text-primary">{item.masteryPercent ?? '—'}%</span></div><p className="workspace-metadata mt-1">{item.answeredCount} câu đã trả lời</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div></div>; })}</div> : <p className="workspace-page-description mt-4">Chưa có đủ dữ liệu theo chuyên đề để hiển thị tiến độ.</p>}<footer className="mt-5 text-center"><Link href="/analytics" className="workspace-button-text text-primary hover:text-primary-hover">Xem phân tích chi tiết →</Link></footer></section>
  </main>;
}
