'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { fetchProtectedJson, getCurrentUser, isUnauthorizedError } from '../../lib/authApi';
import type { LearningOverviewResponse } from '../../lib/apiTypes';

const practiceHref = (topic: string, subtopic: string) => `/practice/topic/${topic}?subtopic=${subtopic}`;

export function LearningDashboardClient() {
  const [data, setData] = useState<LearningOverviewResponse | null>(null);
  const [state, setState] = useState<'loading' | 'guest' | 'error' | 'ready'>('loading');
  useEffect(() => { let active = true; void (async () => { try { if (!await getCurrentUser()) { if (active) setState('guest'); return; } const result = await fetchProtectedJson<LearningOverviewResponse>('/api/me/learning-overview'); if (active) { setData(result); setState('ready'); } } catch (error) { if (active) setState(isUnauthorizedError(error) ? 'guest' : 'error'); } })(); return () => { active = false; }; }, []);
  if (state === 'loading') return <main className="min-h-[60vh] p-8">Đang tải tiến độ học tập…</main>;
  if (state === 'guest') return <main className="mx-auto max-w-3xl p-8"><h1 className="workspace-page-title">Luyện thi Toán cùng ManMath</h1><p className="workspace-page-description mt-3">Đăng nhập để lưu tiến độ, nhận gợi ý luyện tập và theo dõi mastery.</p><Link className="workspace-button-text mt-6 inline-flex rounded-lg bg-primary px-5 py-3 text-white" href="/exams">Khám phá kho đề</Link></main>;
  if (state === 'error' || data === null) return <main className="p-8 text-error">Không tải được dashboard. Hãy thử lại sau.</main>;
  const { overall, nextAction, continueItems, recentActivity, subtopics, topics } = data;
  const weak = subtopics.filter((item) => item.isWeak).slice(0, 3);
  return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6"><header><p className="workspace-eyebrow">Không gian học tập</p><h1 className="workspace-page-title mt-1">Tiến độ luyện thi của bạn</h1><p className="workspace-page-description mt-2">Mastery dựa trên điểm đã chấm; số câu đã trả lời giải thích độ tin cậy.</p></header>
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-xl border border-border bg-surface p-5 shadow-card"><p className="workspace-metadata">Mastery tổng quan</p><p className="mt-2 text-3xl font-bold">{overall.masteryPercent === null ? '—' : `${overall.masteryPercent}%`}</p><p className="workspace-metadata mt-2">{overall.answeredCount} câu đã trả lời · {overall.examQuestionCount} từ đề · {overall.practiceQuestionCount} từ luyện tập</p></article><article className="rounded-xl border border-border bg-surface p-5 shadow-card"><p className="workspace-metadata">Độ tin cậy</p><p className="mt-2 text-2xl font-bold">{overall.confidence === 'usable' ? 'Đủ dữ liệu' : overall.confidence === 'low' ? 'Cần thêm dữ liệu' : 'Chưa đủ dữ liệu'}</p><p className="workspace-metadata mt-2">Câu bỏ trống làm giảm mastery nhưng không tăng mẫu đánh giá.</p></article><article className="rounded-xl border border-border bg-surface p-5 shadow-card"><p className="workspace-metadata">Tiến độ theo nguồn</p><p className="mt-2 text-2xl font-bold">{overall.fullyCorrectCount} câu đúng hoàn toàn</p><p className="workspace-metadata mt-2">Điểm: {overall.earnedScoreUnits}/{overall.maxScoreUnits} score units</p></article></section>
    {continueItems.length > 0 ? <section className="rounded-xl border border-border bg-surface p-5 shadow-card"><h2 className="workspace-section-title">Tiếp tục học</h2>{continueItems.map((item) => <Link key={item.sessionId} className="mt-3 block text-primary" href={`/practice/topic/${item.topicSlug}`}>Tiếp tục phiên luyện tập: {item.title}</Link>)}</section> : null}
    <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-xl border border-border bg-surface p-5 shadow-card"><h2 className="workspace-section-title">Bước tiếp theo</h2>{nextAction ? <><p className="mt-3 font-semibold">{nextAction.title}</p><p className="workspace-page-description mt-1">{nextAction.reason}</p><Link className="workspace-button-text mt-4 inline-flex rounded-lg bg-primary px-4 py-2 text-white" href={practiceHref(nextAction.topicSlug, nextAction.subtopicSlug)}>Luyện 5 câu</Link></> : <p className="workspace-page-description mt-3">Corpus chưa có subtopic đủ câu để đề xuất.</p>}</article><article className="rounded-xl border border-border bg-surface p-5 shadow-card"><h2 className="workspace-section-title">Cần chú ý</h2>{weak.length ? weak.map((item) => <Link key={item.subtopicSlug} className="mt-3 block" href={practiceHref(item.topicSlug, item.subtopicSlug!)}><strong>{item.subtopicName}</strong><span className="workspace-metadata"> · {item.masteryPercent}% · {item.answeredCount} câu đã trả lời</span></Link>) : <p className="workspace-page-description mt-3">Chưa có phần nào đủ dữ liệu để kết luận là cần luyện thêm.</p>}</article></section>
    <section className="rounded-xl border border-border bg-surface p-5 shadow-card"><h2 className="workspace-section-title">Hoạt động gần đây</h2>{recentActivity.length ? <div className="mt-3 divide-y divide-border">{recentActivity.map((item) => <div className="flex justify-between gap-4 py-3" key={`${item.sourceType}-${item.id}`}><span>{item.sourceType === 'exam' ? 'Đề' : 'Luyện tập'} · {item.title}</span><span className="workspace-metadata">{item.fullyCorrectCount}/{item.totalQuestions} đúng hoàn toàn</span></div>)}</div> : <p className="workspace-page-description mt-3">Chưa có hoạt động hoàn thành. Hãy bắt đầu một phiên luyện tập.</p>}</section>
    <section className="rounded-xl border border-border bg-surface p-5 shadow-card"><h2 className="workspace-section-title">Tiến độ theo chuyên đề</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{topics.filter((item) => item.answeredCount > 0).slice(0, 8).map((item) => <div key={item.topicSlug} className="rounded-lg border border-border p-3"><strong>{item.topicName}</strong><p className="workspace-metadata mt-1">{item.masteryPercent ?? '—'}% · {item.answeredCount} câu đã trả lời</p></div>)}</div><Link href="/analytics" className="workspace-button-text mt-4 inline-flex text-primary">Xem phân tích chi tiết</Link></section>
  </main>;
}
