'use client';
import { useEffect, useRef, useState } from 'react';
import { API_BASE_URL } from '../../config/api';
import { getAuthToken } from '../../lib/authStorage';
import { V2QuestionCard } from '../exam-v2/ExamContentTakingClient';
import { Button } from '../ui';
import type { V2AnswerState, V2AnswersByQuestionId, V2PracticeSessionDto, V2SubmittedResponse } from '../exam-v2/types';

type Props = { topicSlug: string };
type Type = 'single_choice' | 'true_false_group' | 'short_answer';
type TopicDto = { readonly slug: string; readonly name: string; readonly subtopics: readonly { readonly slug: string; readonly name: string }[] };
const auth = (): HeadersInit => ({ 'Content-Type': 'application/json', Authorization: `Bearer ${getAuthToken() ?? ''}` });
const key = (id: string): string => { const name = `manmath-practice-submit:${id}`; const old = sessionStorage.getItem(name); if (old) return old; const fresh = crypto.randomUUID(); sessionStorage.setItem(name, fresh); return fresh; };
const answer = (value: V2SubmittedResponse | null): V2AnswerState | undefined => value === null ? undefined : value.type === 'short_answer' ? { type: 'short_answer', value: value.response } : value;

export function PersistentPracticeClient({ topicSlug }: Props) {
  const [session, setSession] = useState<V2PracticeSessionDto | null>(null); const [ready, setReady] = useState(false); const [error, setError] = useState<string | null>(null);
  const [answers, setAnswers] = useState<V2AnswersByQuestionId>({}); const [subtopicSlug, setSubtopicSlug] = useState(''); const [count, setCount] = useState<5 | 10>(5); const [types, setTypes] = useState<readonly Type[]>(['single_choice']); const [topic, setTopic] = useState<TopicDto | null>(null);
  const revisions = useRef(new Map<string, number>()); const timers = useRef(new Map<string, number>()); const chains = useRef(new Map<string, Promise<void>>()); const pending = useRef(new Map<string, V2AnswerState | null>());
  const hydrate = (value: V2PracticeSessionDto): void => { setSession(value); revisions.current = new Map(value.questions.map((item) => [item.sessionQuestionId, item.responseRevision])); setAnswers(Object.fromEntries(value.questions.flatMap((item) => { const saved = answer(item.response); return saved ? [[item.sessionQuestionId, saved]] : []; }))); };
  useEffect(() => { let alive = true; void (async () => { try { const [active, taxonomy] = await Promise.all([fetch(`${API_BASE_URL}/api/v2/practice/sessions/active?topicSlug=${encodeURIComponent(topicSlug)}`, { headers: auth() }), fetch(`${API_BASE_URL}/api/topics`)]); const body = await active.json() as { session: V2PracticeSessionDto | null; message?: string }; const taxonomyBody = await taxonomy.json() as { topics?: readonly TopicDto[] }; if (!active.ok) throw new Error(body.message); if (alive && body.session) hydrate(body.session); if (alive) setTopic(taxonomyBody.topics?.find((item) => item.slug === topicSlug) ?? null); } catch (e) { if (alive) setError(e instanceof Error ? e.message : 'Không thể tải phiên luyện tập.'); } finally { if (alive) setReady(true); } })(); return () => { alive = false; for (const timer of timers.current.values()) clearTimeout(timer); }; }, [topicSlug]);
  const start = async (): Promise<void> => { setError(null); const r = await fetch(`${API_BASE_URL}/api/v2/practice/sessions`, { method: 'POST', headers: auth(), body: JSON.stringify({ topicSlug, subtopicSlug: subtopicSlug || null, questionCount: count, questionTypes: types }) }); const body = await r.json() as V2PracticeSessionDto | { message?: string; code?: string }; if (!r.ok) { setError('message' in body ? body.message ?? 'Chưa có câu phù hợp.' : 'Chưa có câu phù hợp.'); return; } hydrate(body as V2PracticeSessionDto); };
  const save = async (sessionQuestionId: string, next: V2AnswerState | null): Promise<void> => { if (!session) return; const revision = revisions.current.get(sessionQuestionId) ?? 0; const r = await fetch(`${API_BASE_URL}/api/v2/practice/sessions/${session.id}/questions/${sessionQuestionId}/response`, { method: 'PUT', headers: auth(), body: JSON.stringify({ response: next, expectedRevision: revision }) }); const body = await r.json().catch(() => null) as { responseRevision?: number } | null; if (r.status === 409) { setError('Câu trả lời đã thay đổi ở nơi khác. Hãy tải lại phiên.'); return; } if (!r.ok || body?.responseRevision === undefined) { setError('Không thể lưu câu trả lời.'); return; } revisions.current.set(sessionQuestionId, body.responseRevision); };
  const enqueue = (id: string, next: V2AnswerState | null): Promise<void> => { const previous = chains.current.get(id) ?? Promise.resolve(); const queued = previous.catch(() => undefined).then(() => save(id, next)); chains.current.set(id, queued); return queued; };
  const update = (id: string, next: V2AnswerState | null): void => { if (!session || session.status !== 'in_progress') return; pending.current.set(id, next); setAnswers((old) => { const copy = { ...old }; if (next) copy[id] = next; else delete copy[id]; return copy; }); const prior = timers.current.get(id); if (prior) clearTimeout(prior); timers.current.set(id, window.setTimeout(() => { void enqueue(id, next); }, 350)); };
  const submit = async (): Promise<void> => { if (!session) return; await Promise.all([...pending.current.entries()].map(async ([id, next]) => { const timer = timers.current.get(id); if (timer) clearTimeout(timer); await enqueue(id, next); })); const r = await fetch(`${API_BASE_URL}/api/v2/practice/sessions/${session.id}/submit`, { method: 'POST', headers: { ...auth(), 'Idempotency-Key': key(session.id) } }); const body = await r.json() as V2PracticeSessionDto | { message?: string }; if (!r.ok) { setError('message' in body ? body.message ?? 'Không thể nộp bài.' : 'Không thể nộp bài.'); return; } pending.current.clear(); sessionStorage.removeItem(`manmath-practice-submit:${session.id}`); hydrate(body as V2PracticeSessionDto); };
  const cancel = async (): Promise<void> => { if (!session || !window.confirm('Bỏ phiên hiện tại để đổi cấu hình?')) return; const r = await fetch(`${API_BASE_URL}/api/v2/practice/sessions/${session.id}/cancel`, { method: 'POST', headers: auth() }); if (!r.ok) { setError('Không thể bỏ phiên hiện tại.'); return; } setSession(null); setAnswers({}); };
  if (!ready) return <main className="p-8">Đang tải…</main>;
  if (!session) return <main className="mx-auto max-w-xl p-8"><h1 className="text-xl font-bold">Cấu hình luyện tập</h1><p className="mt-2 text-sm">Topic: {topic?.name ?? topicSlug}</p><label className="mt-4 block">Subtopic<select className="mt-1 w-full rounded border p-2" value={subtopicSlug} onChange={(e) => setSubtopicSlug(e.target.value)}><option value="">Tất cả subtopic</option>{topic?.subtopics.map((item) => <option key={item.slug} value={item.slug}>{item.name}</option>)}</select></label><label className="mt-4 block">Số câu<select className="mt-1 w-full rounded border p-2" value={count} onChange={(e) => setCount(Number(e.target.value) as 5 | 10)}><option value={5}>5</option><option value={10}>10</option></select></label><fieldset className="mt-4"><legend>Loại câu</legend>{(['single_choice','true_false_group','short_answer'] as const).map((type) => <label key={type} className="mr-3"><input type="checkbox" checked={types.includes(type)} onChange={() => setTypes((old) => old.includes(type) ? old.filter((x) => x !== type) : [...old, type])} /> {type}</label>)}</fieldset>{error ? <p className="mt-3 text-error">{error}</p> : null}<Button className="mt-5" disabled={types.length === 0 || topic === null} onClick={() => void start()}>Bắt đầu luyện</Button></main>;
  const locked = session.status !== 'in_progress'; return <main className="mx-auto max-w-5xl p-6"><header className="mb-5 rounded border p-4"><h1 className="text-xl font-bold">{session.topic.name}</h1><p>{session.configuration.actualQuestionCount}/{session.configuration.requestedQuestionCount} câu · {session.configuration.questionTypes.join(', ')}</p>{session.status === 'in_progress' ? <><Button className="mt-3" onClick={() => void submit()}>Nộp bài</Button><Button className="mt-3 ml-3" variant="outline" onClick={() => void cancel()}>Đổi cấu hình</Button></> : <p className="mt-3">{session.status === 'completed' ? `Kết quả: ${session.scoreUnits}/${session.maxScoreUnits}` : 'Phiên đã bị bỏ.'}</p>}{error ? <p className="text-error">{error}</p> : null}</header>{session.questions.map((item, index) => <div className="mb-5" key={item.sessionQuestionId}><V2QuestionCard question={item.question} index={index} answer={answers[item.sessionQuestionId]} isTimeUp={locked} onAnswerChange={(next) => update(item.sessionQuestionId, next)} />{!locked ? <Button className="mt-2" variant="outline" onClick={() => update(item.sessionQuestionId, null)}>Xóa câu trả lời</Button> : null}</div>)}</main>;
}
