import { Prisma, QuestionType } from '@prisma/client';
import { createHash, randomBytes } from 'crypto';
import { prisma } from '../lib/prisma';
import type { PublicQuestion, QuestionInput, SubmittedResponse } from '../types/examContent';
import type { PracticeSessionDto } from '../types/examContentApi';
import { gradeQuestionSet } from './examContentGradingService';
import { maximumQuestionScore } from './examGrading';
import { examQuestionProvenanceFingerprint, questionBankItemToQuestion, questionFingerprint } from './questionBankService';
import { validateQuestionInput } from '../types/examContentValidation';

const TYPES: readonly QuestionType[] = ['single_choice', 'true_false_group', 'short_answer'];
const COUNTS = new Set([5, 10]);
export class PracticeSessionRequestError extends Error {}
export class PracticeSessionConflictError extends Error {}
export class PracticeSessionNoMatchingQuestionsError extends PracticeSessionRequestError { readonly code = 'PRACTICE_NO_MATCHING_QUESTIONS'; }
type E = { id:string; externalId:string; examVersionId:string; type:QuestionInput['type']; section:number; order:number; content:string; topicSlug:string; subtopicSlug:string|null; assets:Prisma.JsonValue|null; choices:Prisma.JsonValue|null; statements:Prisma.JsonValue|null; answerKey:Prisma.JsonValue; examVersion?:{examId:string} };
type B = { id:string; logicalKey:string; type:QuestionInput['type']; section:number; sourceOrder:number; content:string; assets:Prisma.JsonValue|null; choices:Prisma.JsonValue|null; statements:Prisma.JsonValue|null; answerKey:Prisma.JsonValue; topic:{slug:string}; subtopic:{slug:string}; provenanceFingerprint:string; contentFingerprint:string };
type S = { examVersionQuestion:E|null; questionBankItem:B|null };
type L = { sourceType:'exam'|'bank'; sourceId:string; provenance:string; contentFingerprint:string; question:QuestionInput };
type C = {topicSlug:string;subtopicSlug:string|null;questionCount:number;questionTypes:readonly QuestionType[]};
const examQuestion=(r:E):QuestionInput=>{const x=validateQuestionInput({id:r.externalId,type:r.type,section:r.section,order:r.order,content:r.content,topicSlug:r.topicSlug,...(r.subtopicSlug===null?{}:{subtopicSlug:r.subtopicSlug}),...(r.assets===null?{}:{assets:r.assets}),...(r.choices===null?{}:{choices:r.choices}),...(r.statements===null?{}:{statements:r.statements}),answerKey:r.answerKey});if(!x.ok)throw new PracticeSessionRequestError(`Pinned question is invalid: ${x.message}`);return x.value;};
function load(r:S):L { if ((r.examVersionQuestion!==null)===(r.questionBankItem!==null)) throw new PracticeSessionRequestError('Pinned practice question must have exactly one source'); if(r.examVersionQuestion){const q=examQuestion(r.examVersionQuestion);return{sourceType:'exam',sourceId:r.examVersionQuestion.id,provenance:examQuestionProvenanceFingerprint(r.examVersionQuestion.examVersion?.examId??r.examVersionQuestion.examVersionId,r.examVersionQuestion.externalId),contentFingerprint:questionFingerprint(q),question:{...q,id:`exam:${r.examVersionQuestion.id}`}as QuestionInput};}const b=r.questionBankItem!;const q=questionBankItemToQuestion(b);return{sourceType:'bank',sourceId:b.id,provenance:b.provenanceFingerprint,contentFingerprint:b.contentFingerprint,question:{...q,id:`bank:${b.id}`}as QuestionInput}; }
const publicQuestion=(q:QuestionInput)=>{const{answerKey,...safe}=q;return safe;};
function response(v:Prisma.JsonValue|null,q:QuestionInput):SubmittedResponse|null{if(v===null)return null;const r=v as Record<string,unknown>;if(r.type!==q.type)throw new PracticeSessionRequestError('Pinned response is invalid');if(q.type==='single_choice'&&typeof r.choiceId==='string')return{type:q.type,choiceId:r.choiceId as never};if(q.type==='short_answer'&&typeof r.response==='string')return{type:q.type,response:r.response as never};if(q.type==='true_false_group'&&typeof r.values==='object'&&r.values!==null)return{type:q.type,values:r.values as Record<never,boolean>};throw new PracticeSessionRequestError('Pinned response is invalid');}
function normalized(v:unknown,q:QuestionInput):SubmittedResponse|null{if(v===null)return null;if(typeof v!=='object'||v===null)throw new PracticeSessionRequestError('Pinned response is invalid');const g=gradeQuestionSet([q],{responses:[{questionId:q.id,...v as Record<string,unknown>}as never]});if(g.results[0]?.response===undefined)throw new PracticeSessionRequestError('Pinned response is invalid');return g.results[0].response;}
function config(raw:unknown):C{if(typeof raw!=='object'||raw===null)throw new PracticeSessionRequestError('Practice configuration is invalid');const b=raw as Record<string,unknown>,topicSlug=typeof b.topicSlug==='string'?b.topicSlug.trim():'',subtopicSlug=b.subtopicSlug==null?null:typeof b.subtopicSlug==='string'?b.subtopicSlug.trim():'';if(!topicSlug||(subtopicSlug!==null&&!subtopicSlug))throw new PracticeSessionRequestError('topicSlug/subtopicSlug is invalid');if(!Number.isInteger(b.questionCount)||!COUNTS.has(b.questionCount as number))throw new PracticeSessionRequestError('questionCount must be 5 or 10');if(!Array.isArray(b.questionTypes)||b.questionTypes.length===0||b.questionTypes.some(x=>typeof x!=='string'||!TYPES.includes(x as QuestionType)))throw new PracticeSessionRequestError('questionTypes is invalid');const set=new Set(b.questionTypes as QuestionType[]);if(set.size!==b.questionTypes.length)throw new PracticeSessionRequestError('questionTypes must not contain duplicates');return{topicSlug,subtopicSlug,questionCount:b.questionCount as number,questionTypes:TYPES.filter(x=>set.has(x))};}
const rank=(seed:string,id:string)=>createHash('sha256').update(`${seed}:${id}`).digest('hex');
function dedupe(xs:readonly L[]):readonly L[]{const exam=xs.filter(x=>x.sourceType==='exam'),banks=xs.filter(x=>x.sourceType==='bank'),p=new Set(exam.map(x=>x.provenance)),c=new Set(exam.map(x=>x.contentFingerprint)),out=[...exam];for(const x of banks){if(p.has(x.provenance)||c.has(x.contentFingerprint))continue;p.add(x.provenance);c.add(x.contentFingerprint);out.push(x);}return out;}
const sourceInclude={answer:true,examVersionQuestion:{include:{examVersion:{select:{examId:true}}}},questionBankItem:{include:{topic:{select:{slug:true}},subtopic:{select:{slug:true}}}}}as const;
async function dto(id:string,userId:string):Promise<PracticeSessionDto|null>{const s=await prisma.practiceSession.findFirst({where:{id,userId},include:{topic:{select:{slug:true,name:true}},subtopic:{select:{slug:true,name:true}},questions:{orderBy:{order:'asc'},include:sourceInclude}}});if(!s)return null;return{id:s.id,status:s.status,topic:s.topic,startedAt:s.startedAt.toISOString(),submittedAt:s.submittedAt?.toISOString()??null,scoreUnits:s.scoreUnits as never,maxScoreUnits:s.maxScoreUnits as never,fullyCorrectCount:s.fullyCorrectCount,totalQuestions:s.totalQuestions,unansweredCount:s.unansweredCount,configuration:{topicSlug:s.topic.slug,subtopicSlug:s.subtopic?.slug??null,requestedQuestionCount:s.requestedQuestionCount,actualQuestionCount:s.totalQuestions,questionTypes:s.selectedQuestionTypes},questions:s.questions.map(e=>{const q=load(e).question,a=e.answer,result=s.status==='completed'&&a?.isFullyCorrect!==null&&a?.isFullyCorrect!==undefined&&a.awardedScoreUnits!==null&&a.maxScoreUnits!==null?{result:{isFullyCorrect:a.isFullyCorrect,awardedScoreUnits:a.awardedScoreUnits as never,maxScoreUnits:a.maxScoreUnits as never}}:{};return{sessionQuestionId:e.id,order:e.order,question:{...publicQuestion(q),id:e.id as PublicQuestion['id']}as PublicQuestion,response:a?response(a.response,q):null,responseRevision:a?.responseRevision??0,...result};})};}
export async function getActivePracticeSession(slug:string,userId:string){const t=await prisma.topic.findUnique({where:{slug},select:{id:true}});if(!t)return null;const a=await prisma.practiceSession.findFirst({where:{userId,topicId:t.id,status:'in_progress'},select:{id:true}});return a?dto(a.id,userId):null;}
export async function openPracticeSession(raw:unknown,userId:string):Promise<{session:PracticeSessionDto;created:boolean}>{if(typeof raw!=='object'||raw===null||typeof(raw as Record<string,unknown>).topicSlug!=='string')throw new PracticeSessionRequestError('topicSlug is invalid');const topicSlug=(raw as Record<string,unknown>).topicSlug as string,t=await prisma.topic.findUnique({where:{slug:topicSlug.trim()},select:{id:true}});if(!t)throw new PracticeSessionRequestError('Topic not found');const active=await prisma.practiceSession.findFirst({where:{userId,topicId:t.id,status:'in_progress'},select:{id:true}});if(active)return{session:(await dto(active.id,userId))!,created:false};const c=config(raw),sub=c.subtopicSlug===null?null:await prisma.subtopic.findFirst({where:{slug:c.subtopicSlug,topicId:t.id},select:{id:true}});if(c.subtopicSlug!==null&&!sub)throw new PracticeSessionRequestError('subtopicSlug does not belong to topicSlug');const [es,bs]=await Promise.all([prisma.examVersionQuestion.findMany({where:{topicSlug,...(c.subtopicSlug===null?{}:{subtopicSlug:c.subtopicSlug}),type:{in:[...c.questionTypes]},examVersion:{status:'published'}},include:{examVersion:{select:{examId:true}}}}),prisma.questionBankItem.findMany({where:{topicId:t.id,...(sub?{subtopicId:sub.id}:{}),type:{in:[...c.questionTypes]},status:'published'},include:{topic:{select:{slug:true}},subtopic:{select:{slug:true}}}})]);const eligible=dedupe([...es.map(x=>load({examVersionQuestion:x,questionBankItem:null})),...bs.map(x=>load({examVersionQuestion:null,questionBankItem:x}))]);if(!eligible.length)throw new PracticeSessionNoMatchingQuestionsError('No published questions match this practice configuration');const seed=randomBytes(24).toString('base64url'),key=(x:L)=>x.sourceType==='exam'?x.sourceId:`bank:${x.sourceId}`,selected=[...eligible].sort((a,b)=>rank(seed,key(a)).localeCompare(rank(seed,key(b)))).slice(0,c.questionCount);try{const made=await prisma.practiceSession.create({data:{userId,topicId:t.id,subtopicId:sub?.id,requestedQuestionCount:c.questionCount,selectedQuestionTypes:[...c.questionTypes],selectionSeed:seed,totalQuestions:selected.length,questions:{create:selected.map((x,i)=>({order:i+1,...(x.sourceType==='exam'?{examVersionQuestionId:x.sourceId}:{questionBankItemId:x.sourceId}),answer:{create:{}}}))}},select:{id:true}});return{session:(await dto(made.id,userId))!,created:true};}catch(e){const w=await prisma.practiceSession.findFirst({where:{userId,topicId:t.id,status:'in_progress'},select:{id:true}});if(w)return{session:(await dto(w.id,userId))!,created:false};throw e;}}
export const getPracticeSession=(id:string,userId:string)=>dto(id,userId);
export async function cancelPracticeSession(id:string,userId:string){const x=await prisma.practiceSession.updateMany({where:{id,userId,status:'in_progress'},data:{status:'cancelled'}});if(x.count!==1)throw new PracticeSessionConflictError('Only an in-progress practice session can be cancelled');}
export async function savePracticeSessionResponse(sessionId:string,questionId:string,userId:string,raw:unknown,expected:unknown){if(typeof expected!=='number'||!Number.isInteger(expected)||expected<0)throw new PracticeSessionRequestError('expectedRevision is invalid');const x=await prisma.practiceSessionQuestion.findFirst({where:{id:questionId,practiceSessionId:sessionId,practiceSession:{userId,status:'in_progress'}},include:sourceInclude});if(!x?.answer)throw new PracticeSessionConflictError('Practice session is unavailable');const q=load(x).question,next=normalized(raw,q),old=response(x.answer.response,q);if(x.answer.responseRevision!==expected){if(JSON.stringify(old)===JSON.stringify(next))return{response:old,responseRevision:x.answer.responseRevision};throw new PracticeSessionConflictError('Practice answer was changed elsewhere');}const u=await prisma.practiceSessionAnswer.update({where:{practiceSessionQuestionId:x.id},data:{response:next===null?Prisma.DbNull:JSON.parse(JSON.stringify(next)),responseRevision:{increment:1}},select:{response:true,responseRevision:true}});return{response:response(u.response,q),responseRevision:u.responseRevision};}
export async function submitPracticeSession(id:string,userId:string,key:string):Promise<{session:PracticeSessionDto;replayed:boolean}>{const current=await prisma.practiceSession.findFirst({where:{id,userId},select:{status:true,submitIdempotencyKey:true}});if(!current)throw new PracticeSessionRequestError('Practice session not found');if(current.status==='completed'){if(current.submitIdempotencyKey!==key)throw new PracticeSessionConflictError('Practice session is already completed');return{session:(await dto(id,userId))!,replayed:true};}if(current.status!=='in_progress')throw new PracticeSessionConflictError('Practice session is unavailable');const s=await prisma.practiceSession.findUnique({where:{id},include:{questions:{orderBy:{order:'asc'},include:sourceInclude}}});if(!s)throw new PracticeSessionRequestError('Practice session not found');const qs=s.questions.map(x=>load(x).question),rs=s.questions.flatMap((x,i)=>{const r=response(x.answer?.response??null,qs[i]!);return r===null?[]:[{questionId:qs[i]!.id,...r}];}),g=gradeQuestionSet(qs,{responses:rs}),by=new Map(g.results.map(x=>[x.questionId,x]));try{await prisma.$transaction(async tx=>{for(const[i,x]of s.questions.entries()){const q=qs[i]!,r=by.get(q.id)!;await tx.practiceSessionAnswer.update({where:{practiceSessionQuestionId:x.id},data:{isFullyCorrect:r.isCorrect,awardedScoreUnits:r.awardedScore,maxScoreUnits:maximumQuestionScore(q)}});}const changed=await tx.practiceSession.updateMany({where:{id,userId,status:'in_progress'},data:{status:'completed',submittedAt:new Date(),scoreUnits:g.totalAwardedScore,maxScoreUnits:qs.reduce((n,q)=>n+maximumQuestionScore(q),0),fullyCorrectCount:g.results.filter(x=>x.isCorrect).length,unansweredCount:g.results.filter(x=>x.response===undefined).length,submitIdempotencyKey:key,submissionFingerprint:createHash('sha256').update(`${userId}:${id}`).digest('hex')}});if(changed.count!==1)throw new PracticeSessionConflictError('Practice session was submitted concurrently');});return{session:(await dto(id,userId))!,replayed:false};}catch(e){const w=await prisma.practiceSession.findFirst({where:{id,userId},select:{status:true,submitIdempotencyKey:true}});if(w?.status==='completed'&&w.submitIdempotencyKey===key)return{session:(await dto(id,userId))!,replayed:true};if(w?.status!=='in_progress')throw new PracticeSessionConflictError('Practice session is unavailable');throw e;}}
