import { MathText } from '../exam/MathText';
import { QuestionImage } from '../exam/QuestionImage';
import type { V2AttemptReviewQuestionDto } from './types';

type AttemptReviewSectionProps = {
  questions: readonly V2AttemptReviewQuestionDto[];
};

const answerLabel = (value: boolean | undefined): string =>
  value === undefined ? 'Chưa trả lời' : value ? 'Đúng' : 'Sai';

export function AttemptReviewSection({ questions }: AttemptReviewSectionProps) {
  return <section className="border-t border-border pt-6"><div><p className="text-sm font-medium text-text-secondary">Review đáp án</p><h2 className="mt-1 text-xl font-bold text-text-primary">Đối chiếu từng câu</h2><p className="mt-2 text-sm leading-6 text-text-secondary">Đáp án được đọc từ snapshot của đề tại thời điểm bạn nộp bài.</p></div><div className="mt-5 space-y-5">{questions.map((question, index) => <article key={question.id} className="rounded-xl border border-border bg-surface shadow-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4"><div><p className="text-sm font-semibold text-text-primary">Câu {index + 1}</p><p className={`mt-1 text-xs font-semibold ${question.isFullyCorrect ? 'text-success' : question.studentResponse === null ? 'text-warning' : 'text-error'}`}>{question.isFullyCorrect ? 'Đúng' : question.studentResponse === null ? 'Chưa làm' : 'Chưa đúng'}</p></div><span className="text-sm font-semibold tabular-nums text-text-primary">{question.awardedScoreUnits} / {question.maxScoreUnits} units</span></div><div className="px-5 py-6"><MathText as="p" text={question.content} className="text-base leading-8 text-text-primary" />{question.assets?.map((asset) => <QuestionImage key={asset.src} imageUrl={asset.src} alt={asset.alt} className="mt-4" />)}
    {question.type === 'single_choice' ? <div className="mt-5 space-y-2">{question.choices.map((choice, choiceIndex) => { const selected = question.studentResponse?.type === 'single_choice' && question.studentResponse.choiceId === choice.id; const correct = question.correctAnswer.correctChoiceId === choice.id; return <div key={choice.id} className={`rounded-lg border p-3 ${correct ? 'border-success-border bg-success-light' : selected ? 'border-error-border bg-error-light' : 'border-border bg-background'}`}><div className="flex gap-3"><span className="font-semibold text-text-primary">{String.fromCharCode(65 + choiceIndex)}.</span><MathText as="div" text={choice.content} className="text-sm leading-6 text-text-primary" /></div><p className="mt-2 text-xs font-medium text-text-secondary">{correct ? 'Đáp án đúng' : selected ? 'Bạn đã chọn' : ''}</p></div>; })}</div> : null}
    {question.type === 'true_false_group' ? <div className="mt-5 space-y-3">{question.statements.map((statement, statementIndex) => { const selected = question.studentResponse?.type === 'true_false_group' ? question.studentResponse.values[statement.id] : undefined; const correct = question.correctAnswer.values[statement.id]; return <div key={statement.id} className="rounded-lg border border-border bg-background p-3"><div className="flex gap-3"><span className="font-semibold text-primary">{String.fromCharCode(97 + statementIndex)})</span><MathText as="div" text={statement.content} className="text-sm leading-6 text-text-primary" /></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><p className="rounded bg-surface px-3 py-2 text-text-secondary">Bạn chọn: <span className="font-semibold text-text-primary">{answerLabel(selected)}</span></p><p className="rounded bg-success-light px-3 py-2 text-success">Đáp án đúng: <span className="font-semibold">{answerLabel(correct)}</span></p></div></div>; })}</div> : null}
    {question.type === 'short_answer' ? <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-border bg-background p-3"><p className="text-xs text-text-secondary">Câu trả lời của bạn</p><p className="mt-1 font-semibold text-text-primary">{question.studentResponse?.type === 'short_answer' ? question.studentResponse.response : 'Chưa trả lời'}</p></div><div className="rounded-lg border border-success-border bg-success-light p-3"><p className="text-xs text-success">Đáp án đúng</p><p className="mt-1 font-semibold text-success">{question.correctAnswer.answer}{question.correctAnswer.tolerance ? ` (sai số: ${question.correctAnswer.tolerance})` : ''}</p></div></div> : null}
  </div></article>)}</div></section>;
}
